spring:
  zipkin:
    baseUrl: http://localhost:9411/
    sender:
      type: kafka
  sleuth:
    sampler:
      probability: 1.0

server:
  port: 8301

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8302/eureka
  instance:
    hostname: localhost

security:
  oauth2:
    client:
      clientId: finance-service
      clientSecret: ${FINANCE_SERVICE_PASSWORD}
      accessTokenUri: http://localhost:9000/api/auth/oauth/token
      grant-type: client_credentials
      scope: server
    resource:
      userInfoUri: http://localhost:9000/api/auth/user/details

alphavantage:
  apikey: '{cipher}AQBntLyHO6fSQo1vHSUWqBlRZ4Eze4yJ31P3y+IbV7nAMozD3jBc9meTrgetzHHR4c5jERbHwb4RtGCM1TzTmJKYHiScsqItQNbIxbn6yvKFsvcTDLMiPg7dpPekreoS4BdX9hHIqCapZXn5EfqLh/GJRs03t5p/sEM5X25/KaTLiVr54H5C+IJ92VXbB9g3jWfqdz7Gwij3sp8/ElRU5Th79NZN6vVttk+FQN+uV7Ah6mRLWie+p7RPVushbGFshCVEeYUCoNrbEPt1YLn6h/fuW9+Nc3E9/dB+nBw64jQTbL3eUBsMODbIt/1E8PjCHia81r5DcUwJV//QbE8HnL1gNJa21jzv4/AWjm4TK8pCmbQLGKW7sQlr2jCDx77HcS8='

feign:
  hystrix:
    enabled:  true

hystrix:
  shareSecurityContext: true
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000

management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream,info,health

sample:
  zipkin:
    # When enabled=false, traces log to the console. When enabled=true traces send to zipkin
    enabled: true

---
spring:
  profiles: production
  zipkin:
    baseUrl: http://zipkin-service:9411/
  kafka:
    bootstrap-servers: kafka-broker:9092

eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery-service:8302/eureka
  instance:
    preferIpAddress: true

security:
  oauth2:
    client:
      accessTokenUri: http://gateway-service:9000/api/auth/oauth/token
    resource:
      userInfoUri: http://gateway-service:9000/api/auth/user/details
