
server:
  port: 9000

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
      - id: authorization-service
        uri: lb://authorization-service
        predicates:
        - Path=/api/auth/**
        filters:
        - StripPrefix=2
        - RemoveRequestHeader=Cookie, Set-Cookie
      - id: analytics-service
        uri: lb://analytics-service
        predicates:
        - Path=/api/analytics/**
        filters:
        - StripPrefix=2
        - RemoveRequestHeader=Cookie, Set-Cookie

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8302/eureka
  instance:
    hostname: localhost

---
spring:
  profiles: production

eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery-service:8302/eureka
  instance:
    preferIpAddress: true
