
server:
  port: 8989

turbine:
  appConfig: finance-service,analytics-service
  aggregator:
    clusterConfig: FINANCE-SERVICE,ANALYTICS-SERVICE

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8302/eureka
  instance:
    hostname: localhost

spring:
  security:
    user:
      name: "admin"
      password: '{cipher}AQCMR8djWp03QoYWIURUqeZg7ndoOwVIg7AsODDOhxSeOJaF+rwhbL393eR5sk083Efx9IDnyxx7ek6L8qUmbwxlDlahFqWtcBHqgBSv8FB+bTzaje1jnspPodjaGy1KStvRdq6PAYuvljMenOEsIzm1mu8YiacDd7Me8yg4BjsMgGz+5qVnea3AfxueOnG4is4bFj4Eff7CHFQCnUVeWxxHFsR4Dcia0Cki4Q9Q84e7jvCRrvSO5nU9RKTogSAzct4owjt2pp8ejFORcGpytH22rlUXCYx2KdOVNY224xwennrRnPyiYr0eC5Qm2MyW6GR5iYyp7pZ42OALskIshYiJh771VjyPSsk5zPV0l1pebd4FNRYCf36U7IVirA5t6Bc='
  boot:
    admin:
      context-path: /admin
      client:
        enabled: false
        auto-registration: false

---
spring:
  profiles: production

eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery-service:8302/eureka
  instance:
    preferIpAddress: true
