spring:
  cloud:
    config:
      server:
        native:
          searchLocations: classpath:/shared
        encrypt:
          enabled: true
  profiles:
     active: native
  security:
    basic:
      enabled: true
    user:
      name: user
      password: ${CONFIG_SERVICE_PASSWORD}

server:
  port: 8888
